# -*- coding: utf-8 -*-
"""
Django settings for realityOneApi project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url
import firebase_admin
from firebase_admin import credentials
import os
from api.packages.keyvault import *

cred = credentials.Certificate("firebase.json")
firebase_admin.initialize_app(cred)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if config('IS_ACTIVE_KEY_VAULT') == '1':
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = get_secret('SECRET-KEY')
    ALLOWED_HOSTS = get_secret('ALLOWED-HOSTS')
    # Database Url
    DATABASE_URL = get_secret('DATABASE-URL')
    # -------------Smtp setup----------
    EMAIL_USE_TLS = True if get_secret('EMAIL-USE-TLS').lower() == 'true' else False
    EMAIL_HOST = get_secret('EMAIL-HOST')
    EMAIL_HOST_USER = get_secret('EMAIL-HOST-USER')
    EMAIL_HOST_PASSWORD = get_secret('EMAIL-HOST-PASSWORD')
    EMAIL_PORT = get_secret('EMAIL-PORT')
    FROM_EMAIL = get_secret('FROM-EMAIL')
    FROM_EMAIL_TEXT = get_secret('FROM-EMAIL-TEXT')
    BASE_URL = get_secret('BASE-URL')
    FRONT_URL = get_secret('FRONT-URL')
    SUBDOMAIN_URL = get_secret('SUBDOMAIN-URL')
    RESET_PASSWORD_URL = get_secret('RESET-PASSWORD-URL')
    FRONT_BASE_URL = get_secret('FRONT-BASE-URL')
    FREE_PLAN_ID = get_secret('FREE-PLAN-ID')
    BROKER_PLAN_ID = get_secret('BROKER-PLAN-ID')
    AGENT_PLAN_ID = get_secret('AGENT-PLAN-ID')
    LIST_PER_PAGE = get_secret('LIST-PER-PAGE')
    CACHE_TTL = get_secret('CACHE-TTL')
    REDIS_CACHE = get_secret('REDIS-CACHE')
    AZURE_BLOB_URL = get_secret('AZURE-BLOB-URL')
    GOOGLE_API_KEY = get_secret('GOOGLE-API-KEY')
    IS_LIVE = get_secret('IS-LIVE')
    INFOBIP_BASE_URL = get_secret('INFOBIP-BASE-URL')
    INFOBIP_API_KEY = get_secret('INFOBIP-API-KEY-NEW')
    INFOBIP_SENDER_ID = get_secret('INFOBIP-SENDER-ID')
    DAILY_MSG_ATTEMPTS = get_secret('DAILY-MSG-ATTEMPTS')
    AZURE_ACCOUNT_KEY = get_secret('AZURE-ACCOUNT-KEY')
    AZURE_CONTAINER_NAME = get_secret('AZURE-CONTAINER-NAME')
    AZURE_CONNECTION_STRING = get_secret('AZURE-CONNECTION-STRING')
    AZURE_ACCOUNT_NAME = get_secret('AZURE-ACCOUNT-NAME')
    AZURE_BLOB_URL = get_secret('AZURE-BLOB-URL')
    REACT_FRONT_URL = get_secret('REACT-FRONT-URL')
    FCM_APP_VERBOSE_NAME = get_secret('FCM-APP-VERBOSE-NAME')
    FCM_SERVER_KEY = get_secret('FCM-SERVER-KEY')
    PAYMENT_GATEWAY_URL = get_secret('PAYMENT-GATEWAY-URL')
    TIME_ZONE = get_secret('TIMEZONE')
    PFX_CERT_PATH = get_secret('PFX-CERT-PATH')
    PFX_KEY_PATH = get_secret('PFX-KEY-PATH')
    PAYMENT_GATEWAY_GET_PAYMENT_ID_URL = get_secret('PAYMENT-GATEWAY-GET-PAYMENT-ID-URL')
    PAYMENT_GATEWAY_AUTHORIZATION_PAYMENT_URL = get_secret('PAYMENT-GATEWAY-AUTHORIZATION-PAYMENT-URL')
    PAYMENT_GATEWAY_CAPTURE_PAYMENT_URL = get_secret('PAYMENT-GATEWAY-CAPTURE-PAYMENT-URL')
    PAYMENT_GATEWAY_VOID_PAYMENT_URL = get_secret('PAYMENT-GATEWAY-VOID-PAYMENT-URL')
    PAYMENT_GATEWAY_REFUND_PAYMENT_URL = get_secret('PAYMENT-GATEWAY-REFUND-PAYMENT-URL')
    PAYMENT_GATEWAY_MAGNATI_ID = get_secret('PAYMENT-GATEWAY-MAGNATI-ID')
    PAYMENT_GATEWAY_MAGNATI_PASSWORD = get_secret('PAYMENT-GATEWAY-MAGNATI-PASSWORD')
    PAYMENT_GATEWAY_MAGNATI_SERVICE_ID = get_secret('PAYMENT-GATEWAY-MAGNATI-SERVICE-ID')
    PAYMENT_GATEWAY_MAGNATI_MERCHANT_ID = get_secret('PAYMENT-GATEWAY-MAGNATI-MERCHANT-ID')
    AUCTION_LOOKUP_API_URL = get_secret('AUCTION-LOOKUP-API-URL')
    AUCTION_LOOKUP_PROJECT_API_KEY = get_secret('AUCTION-LOOKUP-PROJECT-API-KEY')
    AUCTION_LOOKUP_API_EMIRATES_ID = get_secret('AUCTION-LOOKUP-API-EMIRATES-ID')
    QUANTA_API_BASE_URL = get_secret('QUANTA-API-BASE-URL')
    QUANTA_AREA_COMPARISION_API_ENDPOINT = get_secret('QUANTA-AREA-COMPARISION-API-ENDPOINT')
    QUANTA_AVERAGE_SALE_PRICE_API_ENDPOINT = get_secret('QUANTA-AVERAGE-SALE-PRICE-API-ENDPOINT')
    QUANTA_SALE_TREND_API_ENDPOINT = get_secret('QUANTA-SALE-TREND-API-ENDPOINT')
    QUANTA_TOKEN_API_USERNAME = get_secret('QUANTA-TOKEN-API-USERNAME')
    QUANTA_TOKEN_API_PASSWORD = get_secret('QUANTA-TOKEN-API-PASSWORD')
    FCM_SERVER_KEY = get_secret('FCM-SERVER-KEY')
else:
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = config('SECRET_KEY')
    ALLOWED_HOSTS = config('ALLOWED_HOSTS')
    # Database Url
    DATABASE_URL = config('DATABASE_URL')
    # -------------Smtp setup----------
    EMAIL_USE_TLS = config('EMAIL_USE_TLS')
    EMAIL_HOST = config('EMAIL_HOST')
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    EMAIL_PORT = config('EMAIL_PORT')
    FROM_EMAIL = config('FROM_EMAIL')
    FROM_EMAIL_TEXT = config('FROM_EMAIL_TEXT')
    BASE_URL = config('BASE_URL')
    FRONT_URL = config('FRONT_URL')
    SUBDOMAIN_URL = config('SUBDOMAIN_URL')
    RESET_PASSWORD_URL = config('RESET_PASSWORD_URL')
    FRONT_BASE_URL = config('FRONT_BASE_URL')
    FREE_PLAN_ID = config('FREE_PLAN_ID')
    BROKER_PLAN_ID = config('BROKER_PLAN_ID')
    AGENT_PLAN_ID = config('AGENT_PLAN_ID')
    LIST_PER_PAGE = config('LIST_PER_PAGE')
    CACHE_TTL = config('CACHE_TTL')
    REDIS_CACHE = config('REDIS_CACHE')
    AZURE_BLOB_URL = config('AZURE_BLOB_URL')
    GOOGLE_API_KEY = config('GOOGLE_API_KEY')
    IS_LIVE = config('IS_LIVE')
    INFOBIP_BASE_URL = config('INFOBIP_BASE_URL')
    INFOBIP_API_KEY = config('INFOBIP_API_KEY')
    INFOBIP_SENDER_ID = config('INFOBIP_SENDER_ID')
    DAILY_MSG_ATTEMPTS = config('DAILY_MSG_ATTEMPTS')
    AZURE_ACCOUNT_KEY = config('AZURE_ACCOUNT_KEY')
    AZURE_CONTAINER_NAME = config('AZURE_CONTAINER_NAME')
    AZURE_CONNECTION_STRING = config('AZURE_CONNECTION_STRING')
    AZURE_ACCOUNT_NAME = config('AZURE_ACCOUNT_NAME')
    AZURE_BLOB_URL = config('AZURE_BLOB_URL')
    REACT_FRONT_URL = config('REACT_FRONT_URL')
    FCM_APP_VERBOSE_NAME = config('FCM_APP_VERBOSE_NAME')
    FCM_SERVER_KEY = config('FCM_SERVER_KEY')
    PAYMENT_GATEWAY_URL = config('PAYMENT_GATEWAY_URL')
    TIME_ZONE = config('TIMEZONE')
    PFX_CERT_PATH = config('PFX_CERT_PATH')
    PFX_KEY_PATH = config('PFX_KEY_PATH')
    PAYMENT_GATEWAY_GET_PAYMENT_ID_URL = config('PAYMENT_GATEWAY_GET_PAYMENT_ID_URL')
    PAYMENT_GATEWAY_AUTHORIZATION_PAYMENT_URL = config('PAYMENT_GATEWAY_AUTHORIZATION_PAYMENT_URL')
    PAYMENT_GATEWAY_CAPTURE_PAYMENT_URL = config('PAYMENT_GATEWAY_CAPTURE_PAYMENT_URL')
    PAYMENT_GATEWAY_VOID_PAYMENT_URL = config('PAYMENT_GATEWAY_VOID_PAYMENT_URL')
    PAYMENT_GATEWAY_REFUND_PAYMENT_URL = config('PAYMENT_GATEWAY_REFUND_PAYMENT_URL')
    PAYMENT_GATEWAY_MAGNATI_ID = config('PAYMENT_GATEWAY_MAGNATI_ID')
    PAYMENT_GATEWAY_MAGNATI_PASSWORD = config('PAYMENT_GATEWAY_MAGNATI_PASSWORD')
    PAYMENT_GATEWAY_MAGNATI_SERVICE_ID = config('PAYMENT_GATEWAY_MAGNATI_SERVICE_ID')
    PAYMENT_GATEWAY_MAGNATI_MERCHANT_ID = config('PAYMENT_GATEWAY_MAGNATI_MERCHANT_ID')
    AUCTION_LOOKUP_API_URL = config('AUCTION_LOOKUP_API_URL')
    AUCTION_LOOKUP_PROJECT_API_KEY = config('AUCTION_LOOKUP_PROJECT_API_KEY')
    AUCTION_LOOKUP_API_EMIRATES_ID = config('AUCTION_LOOKUP_API_EMIRATES_ID')
    QUANTA_API_BASE_URL = config('QUANTA_API_BASE_URL')
    QUANTA_AREA_COMPARISION_API_ENDPOINT = config('QUANTA_AREA_COMPARISION_API_ENDPOINT')
    QUANTA_AVERAGE_SALE_PRICE_API_ENDPOINT = config('QUANTA_AVERAGE_SALE_PRICE_API_ENDPOINT')
    QUANTA_SALE_TREND_API_ENDPOINT = config('QUANTA_SALE_TREND_API_ENDPOINT')
    QUANTA_TOKEN_API_USERNAME = config('QUANTA_TOKEN_API_USERNAME')
    QUANTA_TOKEN_API_PASSWORD = config('QUANTA_TOKEN_API_PASSWORD')
    FCM_SERVER_KEY = config('FCM_SERVER_KEY')

ALLOWED_HOSTS = [ALLOWED_HOSTS]
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'oauth2_provider',
    'fcm_django',
    'api.packages',
    'api.users',
    'api.settings',
    'api.payments',
    'api.cms',
    'api.home',
    'api.notifications',
    'api.property',
    'api.project',
    'api.network',
    'api.contact',
    'api.faq',
    'api.bid',
    'api.blog',
    'api.advertisement',
    'api.cron',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# CORS_ALLOWED_ORIGINS = ["http://localhost:3000","http://127.0.0.1:3000",config("FRONT_URL"),config("REACT_FRONT_URL"), "https://uatpayment.magnati.com"]
# CSRF_TRUSTED_ORIGINS = ["http://localhost:3000","http://127.0.0.1:3000",config("FRONT_URL"),config("REACT_FRONT_URL"), "https://uatpayment.magnati.com"]
CORS_ALLOWED_ORIGINS = ["http://localhost:3000","http://127.0.0.1:3000","http://localhost:5173",FRONT_URL,REACT_FRONT_URL, PAYMENT_GATEWAY_URL]
CSRF_TRUSTED_ORIGINS = ["http://localhost:3000","http://127.0.0.1:3000","http://localhost:5173",FRONT_URL,REACT_FRONT_URL, PAYMENT_GATEWAY_URL]
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE", "OPTIONS",]
CORS_ALLOW_HEADERS = ["accept", "authorization", "content-type", "user-agent", "x-csrftoken", "x-requested-with",]
ROOT_URLCONF = 'realityOneApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'realityOneApi.wsgi.application'
DEFAULT_AUTO_FIELD='django.db.models.AutoField'


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL
    )
}

#  ==============OAuth2 Setup=================
# OAUTH2_PROVIDER = {
#     # this is the list of available scopes
#     'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
# }

OAUTH2_PROVIDER = {
    # 'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 15,
    # 'OAUTH_SINGLE_ACCESS_TOKEN': True,
    # 'OAUTH_DELETE_EXPIRED': True,
    # 'ALLOWED_REDIRECT_URI_SCHEMES': ["http", "https"]
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 10,  # 10 minute
    'REFRESH_TOKEN_EXPIRE_SECONDS': 7 * 24 * 60 * 60,  # 7 days
 }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ]
}

# ---------------Redis Cache Setup--------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:7379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "mysecret"
        }
    }
}

# ------------Django Fcm------------
FCM_DJANGO_SETTINGS = {
    "APP_VERBOSE_NAME": FCM_APP_VERBOSE_NAME,
    "FCM_SERVER_KEY": FCM_SERVER_KEY,
    "ONE_DEVICE_PER_USER": False,
    "DELETE_INACTIVE_DEVICES": False,
    "USER_MODEL": "users.Users",
}

# BASE_DIR_FCM = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# FIREBASE_CRED_PATH = os.path.join(BASE_DIR_FCM, "firebase.json")
# if not firebase_admin._apps:
#     cred = credentials.Certificate(FIREBASE_CRED_PATH)
#     firebase_admin.initialize_app(cred)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = config('TIMEZONE')

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
AUTH_USER_MODEL = 'users.Users'