PROPERTY_CSV_HEADING = [
    'Asset Type',
    'Property Type',
    'Property Sub Type',
    'Beds',
    'Baths',
    'Square Footage',
    'Total Acres',
    'Year Built',
    'Country',
    'Address',
    'Zip Code',
    'City',
    'State',
    'Auction type',
    'Bidding Starting Time',
    'Bidding Ending Time',
    'Offer Starting Time',
    'Offer Ending Time',
    'Open House Start Date',
    'Open House End Date',
    'Bid Minimum Price',
    'Reserve Amount',
    'Bid Increments',
    'Asking Price',
    'Due Diligence Period',
    'Escrow Period',
    'Highest and Best Auction Format',
    'Auction Location',
    'Is Featured listing',
    'Buyers Premium',
    'Buyers Premium %',
    'Buyers Premium Minimum Amount',
    'About Property',
    'Terms of Sale'
]