# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views
from api.bid.views import *

urlpatterns = [
    path("bid-registration-detail/", BidRegistrationDetailView.as_view()),
    # path("bid-registration/", BidRegistrationView.as_view()),
    path("bid-registration/", BidsRegistrationView.as_view()),
    path("front-bid-registration/", FrontBidsRegistrationView.as_view()),
    path("bid-registration-proof-upload/", BidRegistrationProofUploadView.as_view()),
    path("subdomain-bid-registration-listing/", SubdomainBidRegistrationListingView.as_view()),
    path("subdomain-bid-registration-detail/", SubdomainBidRegistrationDetailView.as_view()),
    path("update-subdomain-bid-registration/", UpdateSubdomainBidRegistrationView.as_view()),
    path("subdomain-delete-bid-registration/", SubdomainDeleteBidRegistrationView.as_view()),
    path("subdomain-delete-registration-upload/", SubdomainDeleteRegistrationUploadView.as_view()),
    path("super-admin-delete-registration-upload/", SuperAdminDeleteRegistrationUploadView.as_view()),
    path("subdomain-bid-registration-suggestion/", SubdomainBidRegistrationSuggestionView.as_view()),
    path("super-admin-bid-registration-listing/", SuperAdminBidRegistrationListingView.as_view()),
    path("super-admin-bid-registration-detail/", SuperAdminBidRegistrationDetailView.as_view()),
    path("update-super-admin-bid-registration/", UpdateSuperAdminBidRegistrationView.as_view()),
    path("subdomain-property-registration-suggestion/", SubdomainPropertyRegistrationSuggestionView.as_view()),
    path("bid-registration-listing/", BidRegistrationListingView.as_view()),
    path("subdomain-bid-history/", SubdomainBidHistoryView.as_view()),
    path("super-admin-bid-history/", SuperAdminBidHistoryView.as_view()),
    path("bid-history/", BidHistoryView.as_view()),
    path("auction-bidders/", AuctionBiddersView.as_view()),
    path("auction-offers/", AuctionOffersView.as_view()),
    path("auction-total-bids/", AuctionTotalBidsView.as_view()),
    path("auction-total-watching/", AuctionTotalWatchingView.as_view()),
    path("buyer-offer-detail/", BuyerOfferDetailView.as_view()),
    path("best-counter-buyer-offer-detail/", BestCounterBuyerOfferDetailView.as_view()),
    path("best-counter-seller-offer-detail/", BestCounterSellerOfferDetailView.as_view()),
    path("seller-offer-listing/", SellerOfferListingView.as_view()),
    path("seller-offer-detail/", SellerOfferDetailView.as_view()),
    path("check-agent/", CheckAgentView.as_view()),
    path("buyer-make-offer/", BuyerMakeOfferView.as_view()),
    path("seller-counter-offer/", SellerCounterOfferView.as_view()),
    path("buyer-accept-offer/", BuyerAcceptOfferView.as_view()),
    path("seller-accept-offer/", SellerAcceptOfferView.as_view()),
    path("offer-detail/", OfferDetailView.as_view()),
    path("my-offer-listing/", MyOfferListingView.as_view()),
    path("best-offer-listing/", BestOfferListingView.as_view()),
    path("enhanced-best-offer-listing/", EnhancedBestOfferListingView.as_view()),
    path("buyer-reject-offer/", BuyerRejectOfferView.as_view()),
    path("seller-reject-offer/", SellerRejectOfferView.as_view()),
    path("enhanced-buyer-reject-offer/", EnhancedBuyerRejectOfferView.as_view()),
    path("enhanced-seller-reject-offer/", EnhancedSellerRejectOfferView.as_view()),
    path("admin-offer-listing/", AdminOfferListingView.as_view()),
    path("admin-offer-detail/", AdminOfferDetailView.as_view()),
    path("clear-offer/", ClearOfferView.as_view()),
    path("admin-clear-offer/", AdminClearOfferView.as_view()),
    path("get-offer-documents/", GetOfferDocumentsView.as_view()),
    path("send-bid-email/", SendBidEmailView.as_view()),
    path("best-final-detail/", BestFinalDetailView.as_view()),
    path("enhanced-best-final-detail/", EnhancedBestFinalDetailView.as_view()),
    path("buyer-make-loi/", BuyerMakeLoiView.as_view()),
    path("make-loi/", MakeLoiView.as_view()),
    path("enhanced-buyer-make-loi/", EnhancedBuyerMakeLoiView.as_view()),
    path("enhanced-make-loi/", EnhancedMakeLoiView.as_view()),
    path("get-loi/", GetLoiView.as_view()),
    path("bid-delete/", BidDelete.as_view()),
    path("send-loi/", SendLoiView.as_view()),
    path("buyer-accept-loi/", BuyerAcceptLoiView.as_view()),
    path("seller-accept-loi/", SellerAcceptLoiView.as_view()),
    path("enhanced-buyer-accept-loi/", EnhancedBuyerAcceptLoiView.as_view()),
    path("enhanced-seller-accept-loi/", EnhancedSellerAcceptLoiView.as_view()),
    path("best-seller-offer-listing/", BestSellerOfferListingView.as_view()),
    path("enhanced-best-seller-offer-listing/", EnhancedBestSellerOfferListingView.as_view()),
    path("best-seller-offer-detail/", BestSellerOfferDetailView.as_view()),
    path("best-buyer-offer-detail/", BestBuyerOfferDetailView.as_view()),
    path("enhanced-best-seller-offer-detail/", EnhancedBestSellerOfferDetailView.as_view()),
    path("enhanced-best-buyer-offer-detail/", EnhancedBestBuyerOfferDetailView.as_view()),
    path("best-current-offer/", BestCurrentOfferView.as_view()),
    path("enhanced-best-current-offer/", EnhancedBestCurrentOfferView.as_view()),
    path("buyer-accept-best-offer/", BuyerAcceptBestOfferView.as_view()),
    path("seller-accept-best-offer/", SellerAcceptBestOfferView.as_view()),
    path("enhanced-buyer-accept-best-offer/", EnhancedBuyerAcceptBestOfferView.as_view()),
    path("enhanced-seller-accept-best-offer/", EnhancedSellerAcceptBestOfferView.as_view()),
    path("enhanced-best-seller-counter-offer/", EnhancedBestSellerCounterOfferView.as_view()),
    path("best-offer-history-detail/", BestOfferHistoryDetailView.as_view()),
    path("super-admin-best-seller-offer-listing/", SuperAdminBestSellerOfferListingView.as_view()),
    path("super-admin-best-seller-offer-detail/", SuperAdminBestSellerOfferDetailView.as_view()),
    path("super-admin-best-offer-history-detail/", SuperAdminBestOfferHistoryDetailView.as_view()),
    path("super-admin-get-loi/", SuperAdminGetLoiView.as_view()),
    path("super-admin-send-loi/", SuperAdminSendLoiView.as_view()),
    path("send-dutch-email/", SendDutchEmailView.as_view()),
    path("send-sealed-email/", SendSealedEmailView.as_view()),
    path("send-english-email/", SendEnglishEmailView.as_view()),
    path("insider-bidder/", InsiderBidderView.as_view()),
    path("send-english-end-email/", SendEnglishEndEmailView.as_view()),
    path("send-sealed-end-email/", SendSealedEndEmailView.as_view()),
    path("inline-bidding-listing/", InlineBiddingListingView.as_view()),
    path("superadmin-inline-bidding-listing/", SuperAdminInlineBiddingListingView.as_view()),
    path("superadmin-inline-bidding-monitor/", SuperAdminInlineBiddingMonitorView.as_view()),
    path("subdomain-inline-bidding-monitor/", SubdomainInlineBiddingMonitorView.as_view()),
    path("new-bid-registration/", NewBidsRegistrationView.as_view()),
    path("deposit-bid-registration/", DepositBidsRegistrationView.as_view()),
    path("send-english-auction-email/", SendEnglishAuctionEmailView.as_view()),
    path("user-bid-history/", UserBidHistoryView.as_view()),
    path("total-bid-history/", TotalBidHistoryView.as_view()),
    path("super-admin-delete-bid-registration/", SuperAdminDeleteBidRegistrationView.as_view()),
    path("bid-deposit-success/", BidDepositSuccessView.as_view()),
    path("subdomain-bid-registration-listing-export/", SubdomainBidRegistrationListingExportView.as_view()),
    path("user-bid-history-export/", UserBidHistoryExportView.as_view()),
    path("auction-total-bids-export/", AuctionTotalBidsExportView.as_view()),
    path("auction-bidders-export/", AuctionBiddersExportView.as_view()),
    path("auction-total-watching-export/", AuctionTotalWatchingExportView.as_view()),
    # path("bidding-payment-success/", BiddingPaymentSuccessView.as_view()),
    # path("bidding-payment-error/", BiddingPaymentErrorView.as_view()),
    path('bidding-payment-success/', views.bidding_payment_success, name='bidding-payment-success'),
    path('bidding-payment-error/', views.bidding_payment_error, name='bidding-payment-error'),
    path("start-purchase-or-forefit-property/", StartPurchaseOrForefitProperty.as_view()),
    path("property-forefit/", PropertyForefitApiView.as_view()),
    path("retract-bid-buyer/", RetractBidBuyerApiView.as_view()),
    path("update-failed-payment-status/", UpdateFailedPaymentStatusApiView.as_view()),
    path("make-highest-bid/", MakeHighestBidApiView.as_view()),
    path("highest-bidder-details/", HighestBidderDetailsApiView.as_view()),
    path("winner-email/", WinnerEmailApiView.as_view()),
]
